### ISSUE TITLE
how to parse string[] parameters? 

### ISSUE THREAD

**Issue by vivid216** [OrleansContrib/Orleans.Http#37]
` [HttpGet("{grainId}/Positions")]`
 ` Task<IList<PositionState>> QueryPositions([FromQuery] string[] accList);`

**_so the request url is grains/abc/Positions?accList={pzy} or ?accList=[pzy,pzz]  or how to pass the array parameters ? thanks_**

`System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.String[]'.

   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)

   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)

   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Orleans.Http.GrainInvoker.Invoke(IGrain grain, HttpContext context)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by vivid216** [comment]
use [frombody], post data from body is work well. 
close
